spring.application.name=api-gateway
server.port=8095

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Gateway Discovery
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Manual Routes

# user-service
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=lb://user-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**,/api/users/**

# post-service
spring.cloud.gateway.routes[1].id=post-service
spring.cloud.gateway.routes[1].uri=lb://post-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/posts/**

# actuator
management.endpoints.web.exposure.include=*