spring.application.name=api-gateway

# Render Port
server.port=${PORT:8095}

# Eureka
eureka.client.service-url.defaultZone=${EUREKA_URL}

# Gateway Discovery
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# ==========================
# USER SERVICE ROUTES
# ==========================
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=lb://user-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**,/api/users/**,/api/user/**,/api/messages/**,/api/notifications/**,/api/connections/**,/api/events/**,/ws/**

# ==========================
# POST SERVICE ROUTES
# ==========================
spring.cloud.gateway.routes[1].id=post-service
spring.cloud.gateway.routes[1].uri=lb://post-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/posts/**

# ==========================
# ACTUATOR
# ==========================
management.endpoints.web.exposure.include=health,info

# ==========================
# CORS CONFIGURATION
# ==========================
spring.cloud.gateway.globalcors.add-to-simple-url-handler-mapping=true

spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOriginPatterns=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS,PATCH
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true

# ==========================
# REQUEST LIMIT
# ==========================
spring.codec.max-in-memory-size=10MB
